add icarus mode

diff --git a/verify/sim/Makefile b/verify/sim/Makefile
--- a/verify/sim/Makefile
+++ b/verify/sim/Makefile
@@ -1,7 +1,18 @@
 # tb_top name
 tc =  tb_top
 
+glbl_src        = /opt/vivado/glbl.v
+vivado_dir      = /opt/vivado/data/verilog/src
+vivado_xpm_dir  = /opt/vivado/data/ip/xpm
+vivado_lib      = -y$(vivado_dir) \
+                  -y$(vivado_dir)/retarget \
+                  -y$(vivado_dir)/unifast \
+                  -y$(vivado_dir)/unimacro \
+                  -y$(vivado_dir)/unisims \
+                  -y$(vivado_dir)/xeclib \
+
 verdi_opts = -P $(VERDI_HOME)/share/PLI/VCS/LINUX64/novas.tab $(VERDI_HOME)/share/PLI/VCS/LINUX64/pli.a
+i_source_file = $(shell cat ./filelist.f)
 
 rtl_list = ../../design/rtl
 commonip_list = ../../design/common_ip
@@ -25,7 +36,7 @@ compile:
 				+v2k \
 				-full64 \
 				-work xil_defaultlib \
-				"/opt/vivado/glbl.v" \
+				$(glbl_src) \
 				+incdir+${include_list} \
 				-sverilog \
 				+define+SIMULATION_EN \
@@ -75,10 +86,46 @@ verdi:
 				+v2k \
 				$(tb_files) \
 				-F ./filelist.f \
-				-ssf *.fsdb \
+				-ssf *.fsdb\
+				-nologo &
+
+clean:
+				rm -rf  *.key *.vpd DVEfiles coverage *.vdb  novas* verdiLog vfastLog *.mr *.pvl *.syn *.svf ./filelist.f simv.daidir *.log *.fsdb  **.vcd *.vvp simv vcs_lib 64
+
+mklisti:
+				rm -rf ./filelist.f
+				touch ./filelist.f
+				find  $(rtl_list) -type f \( -name "*.v" -o -name "*.sv" \) >> filelist.f
+
+compile_iverilog:
+				iverilog -g2012 -I $(include_list) -o "$(tc).vvp" $(vivado_lib) $(glbl_src) $(tb_files) $(i_source_file)
+
+sim_iverilog:
+				vvp "$(tc).vvp"
+
+gtk:
+				gtkwave "$(tc).vcd"
+
+verdi_iverilog:
+				@echo "Are you sure you want to run make verdi? (y/n)"
+				@read -p "Enter choice: " choice; \
+				if [ "$$choice" != "y" ]; then \
+					echo "Aborting..."; \
+					exit 1; \
+				fi
+				@echo "Proceeding with make verdi..."
+				verdi \
+				-sv \
+				+v2k \
+				+incdir+${include_list} \
+				$(tb_files) \
+				-F ./filelist.f \
+				-ssf *.fsdb\
 				-nologo &
 
 
-clean:
-				rm -rf  *.key *.vpd DVEfiles coverage *.vdb  novas* verdiLog vfastLog *.mr *.pvl *.syn *.svf ./filelist.f simv.daidir *.log *.fsdb  simv vcs_lib 64
+alli: mklisti compile_iverilog sim_iverilog
 
+alliv:mklisti compile_iverilog sim_iverilog verdi_iverilog
+
+allig:mklisti compile_iverilog sim_iverilog gtk
